package com.distributor.backend.entity;

import java.io.Serializable;
import java.util.Objects;

public class PurchaseListId implements Serializable {

    private Long billNumber;
    private Long itemId;

    public PurchaseListId() {}

    public PurchaseListId(Long billNumber, Long itemId) {
        this.billNumber = billNumber;
        this.itemId = itemId;
    }

    // equals and hashCode — generated by IDE or manually

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PurchaseListId)) return false;
        PurchaseListId that = (PurchaseListId) o;
        return Objects.equals(billNumber, that.billNumber) &&
               Objects.equals(itemId, that.itemId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(billNumber, itemId);
    }

    // getters and setters (optional but good practice)
}
